review_version: 5.0
bookname: Blockchain_Biz
language: ja
booktitle:
  { name: "ブロックチェーンで切り拓く未来　Blockchain: Shaping the Future", file-as: "" }
aut: ["Blockchain Biz Community"]
date: 2024-05-26
history: [["2024-05-26"]]
debug: null
chapterlink: true
stylesheet: ["style.css"]

epubversion: 3
htmlversion: 5
toclevel: 2
secnolevel: 2
toc: true
titlepage: false
colophon: true

catalogfile: catalog.yml

epubmaker:
  htmlext: xhtml
  cover_linear: yes

# LaTeX用のスタイルファイル(styディレクトリ以下に置くこと)
texstyle: ["reviewmacro"]

# LaTeX用のdocumentclassを指定する
# オプションについてはsty/README.mdを参照
# デフォルトは印刷用。電子配布版を作るには media=ebook とする
texdocumentclass: ["review-jsbook", "media=print,paper=a5"]

# LaTeX用のコマンドを指定する
texcommand: "uplatex"

# LaTeXのコマンドに渡すオプションを指定する
texoptions: "-interaction=nonstopmode -file-line-error -halt-on-error"

# LaTeX用のdvi変換コマンドを指定する(dvipdfmx)
dvicommand: "dvipdfmx"

# LaTeX用のdvi変換コマンドのオプションを指定する。変換が遅い場合は`-d 5 -z 3`等にする
dvioptions: "-d 5 -z 9"

# PDF生成用の設定
pdfmaker:
  # 画像のscale=X.Xという指定を画像拡大縮小率からページ最大幅の相対倍率に変換する
  image_scale2width: true
  
  # 画像のデフォルトのサイズを、版面横幅合わせではなく、原寸をそのまま利用する
  use_original_image_size: null
  
  # PDFやIllustratorファイル(.ai)の画像のBoudingBoxの抽出に指定のボックスを採用する
  # cropbox(デフォルト), mediabox, artbox, trimbox, bleedboxから選択する。
  # Illustrator CC以降のIllustratorファイルに対してはmediaboxを指定する必要がある
  bbox: mediabox
  
  # 奥付を作成するか。trueを指定するとデフォルトの奥付、ファイル名を指定するとそれがcolophon.htmlとしてコピーされる
  colophon: true
  
  # 表紙挿入時に表紙のページ番号名を「cover」とし、偶数ページ扱いにして大扉前に白ページが入るのを防ぐ。デフォルトはtrue
  use_cover_nombre: true
